# ! Version 3.6 is the latest version of docker-compose
# * not need to write

# ? version: '3.6'

# * services:
services:
  # * database:
  database:
    # ? sql_image
    image: mysql:8.0

    # ? set environment variables
    environment:
      MYSQL_ROOT_PASSWORD: Johnny02
      MYSQL_DATABASE: flightdb

    # ? volumes for persisting data
    volumes:
      - "mysql-data:/var/lib/mysql"

    # ? expose ports(port mapping)
    ports: "3307:3306"

    # ? healthcheck for checking the status of the container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    # ? networks for connecting to other services
    networks:
      - my_network

  # * FlightService:
  myModule:
    image: johnnynaorem/flight_management_project:target
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: Johnny02
      MYSQL_PORT: 3306

    networks:
      - my_network
    ports:
      - "8090:8080"

    # ? Flight Service depends on DB Service, so it waits for the database to be ready
    depends_on:
      - database:
          condition: service_healthy

# ? volumes:
volumes:
  mysql-data:

# ? networks:
networks:
  my_network:
    driver: bridge
